apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: wazibo-server
  name: web-controller
spec:
  replicas: 1
  selector:
    name: wazibo-server
  template:
    metadata:
      labels:
        name: wazibo-server
    spec:
      containers:
      - image: us.gcr.io/wazibo-1143/wazibo-server
        imagePullPolicy: Always
        env:
          - name: WAZIBO_URL
            value: "http://104.196.23.125"
        name: wazibo-server
        ports:
        - containerPort: 9080